#!/usr/bin/env python3
# Copyright 2026 selfcar contributors
# SPDX-License-Identifier: Apache-2.0
from selfcar_obstacle_timeout_replan.aeb_cloud_node import main

if __name__ == "__main__":
    main()
