# Copyright 2026 selfcar contributors
# SPDX-License-Identifier: Apache-2.0

"""Match VTD's sampled box edges while preserving unclaimed/ambiguous points."""

import numpy as np
from sensor_msgs.msg import PointCloud2, PointField
from autoware_perception_msgs.msg import PredictedObject, PredictedObjects, Shape


def rotation(quaternion):
    q = np.array([quaternion.x, quaternion.y, quaternion.z, quaternion.w], dtype=float)
    norm = np.linalg.norm(q)
    if not np.isfinite(norm) or norm < 0.9 or norm > 1.1:
        raise ValueError("invalid quaternion")
    x, y, z, w = q / norm
    return np.array([
        [1 - 2*(y*y + z*z), 2*(x*y - z*w), 2*(x*z + y*w)],
        [2*(x*y + z*w), 1 - 2*(x*x + z*z), 2*(y*z - x*w)],
        [2*(x*z - y*w), 2*(y*z + x*w), 1 - 2*(x*x + y*y)],
    ])


def associate_detection_boxes(tracked, detected, ignored_ids, max_distance=0.5):
    """Use UUIDs from tracking and the exact boxes used to create the VTD cloud.

    Each detection must match exactly one track and vice versa. Ambiguous and
    newly detected actors are given no exclusion and protect their entire box.
    Tracking may change a pedestrian's shape to CYLINDER; that shape is never used
    to erase a box-shaped cloud generated by the bridge.
    """
    if tracked.header.frame_id != detected.header.frame_id:
        raise ValueError("detection/tracking frame mismatch")
    if not np.isfinite(max_distance) or max_distance <= 0:
        raise ValueError("invalid association distance")
    dt = (detected.header.stamp.sec - tracked.header.stamp.sec
          + (detected.header.stamp.nanosec - tracked.header.stamp.nanosec) * 1e-9)
    positions = []
    for obj in tracked.objects:
        pose = obj.kinematics.initial_pose_with_covariance.pose
        velocity = obj.kinematics.initial_twist_with_covariance.twist.linear
        try:
            position = np.array([pose.position.x, pose.position.y, pose.position.z])
            position += rotation(pose.orientation) @ np.array([velocity.x, velocity.y, velocity.z]) * dt
        except ValueError:
            position = np.full(3, np.nan)
        positions.append(position[:2])
    positions = np.asarray(positions).reshape(-1, 2)
    candidates = []
    for obj in detected.objects:
        pose = obj.kinematics.pose_with_covariance.pose
        distances = np.linalg.norm(positions - [pose.position.x, pose.position.y], axis=1)
        candidates.append(np.flatnonzero(distances <= max_distance))
    counts = np.zeros(len(tracked.objects), dtype=int)
    for indices in candidates:
        counts[indices] += 1
    output = PredictedObjects()
    output.header = detected.header
    matched = set()
    for detection, indices in zip(detected.objects, candidates):
        obj = PredictedObject()
        obj.kinematics.initial_pose_with_covariance = detection.kinematics.pose_with_covariance
        obj.kinematics.initial_twist_with_covariance = detection.kinematics.twist_with_covariance
        obj.shape = detection.shape
        if len(indices) == 1 and counts[indices[0]] == 1:
            uid = bytes(tracked.objects[indices[0]].object_id.uuid)
            if uid in ignored_ids and uid != bytes(16):
                obj.object_id.uuid = list(uid)
                matched.add(uid)
        output.objects.append(obj)
    return output, matched


def cloud_views(cloud):
    if cloud.height < 1 or cloud.point_step < 1:
        raise ValueError("invalid cloud dimensions")
    if cloud.row_step < cloud.width * cloud.point_step:
        raise ValueError("invalid cloud row stride")
    required = ((cloud.height - 1) * cloud.row_step + cloud.width * cloud.point_step)
    if len(cloud.data) < required:
        raise ValueError("truncated cloud")
    fields = {field.name: field for field in cloud.fields}
    formats, offsets = [], []
    for name in ("x", "y", "z"):
        field = fields.get(name)
        if field is None or field.count != 1:
            raise ValueError("missing scalar coordinate")
        sizes = {PointField.FLOAT32: ("f4", 4), PointField.FLOAT64: ("f8", 8)}
        if field.datatype not in sizes:
            raise ValueError("unsupported coordinate datatype")
        fmt, size = sizes[field.datatype]
        if field.offset < 0 or field.offset + size > cloud.point_step:
            raise ValueError("coordinate outside point record")
        formats.append((">" if cloud.is_bigendian else "<") + fmt)
        offsets.append(field.offset)
    dtype = np.dtype({"names": ["x", "y", "z"], "formats": formats,
                      "offsets": offsets, "itemsize": cloud.point_step})
    view = np.ndarray((cloud.height, cloud.width), dtype=dtype, buffer=cloud.data,
                      strides=(cloud.row_step, cloud.point_step))
    xyz = np.column_stack([view[name].reshape(-1) for name in ("x", "y", "z")])
    records = np.ndarray((cloud.height, cloud.width, cloud.point_step), dtype=np.uint8,
                         buffer=cloud.data, strides=(cloud.row_step, cloud.point_step, 1))
    return xyz, records.reshape(-1, cloud.point_step)


def filter_cloud(cloud, objects, ignored_ids, transform, *, margin=0.1, z_is_ground=True):
    """Return (cloud, removed_count). Unchanged messages retain their exact bytes.

    transform maps the object frame into the cloud frame at the cloud timestamp.
    Match the bridge's yaw-only cloud projection even when ego TF has roll/pitch.
    VTD flattens tracked object z to ground; its synthetic cloud still has box height.
    Only points close to TWO box faces (an edge) can belong to a VTD box wireframe.
    Any non-excluded object's expanded volume protects its points from exclusion.
    """
    if not ignored_ids or not objects.objects or cloud.width * cloud.height == 0:
        return cloud, 0
    if not np.isfinite(margin) or margin < 0:
        raise ValueError("invalid matching margin")
    xyz, records = cloud_views(cloud)
    cloud_rotation = rotation(transform.rotation)
    translation = np.array([transform.translation.x, transform.translation.y,
                            transform.translation.z])
    if not np.isfinite(translation).all():
        raise ValueError("invalid transform")
    # publish_vtd_obstacle_pointcloud subtracts ego position and rotates XY by
    # ego yaw only. Its base_link-labelled wireframe does not include ego tilt.
    # Recover the map-frame ego origin BEFORE dropping roll/pitch: keeping the
    # full-TF translation with a yaw-only rotation shifts the entire cloud.
    ego_rotation = cloud_rotation.T
    ego_position = -(ego_rotation @ translation)
    ego_yaw = np.arctan2(ego_rotation[1, 0], ego_rotation[0, 0])
    cosine, sine = np.cos(ego_yaw), np.sin(ego_yaw)
    cloud_rotation = np.array([[cosine, sine, 0.0], [-sine, cosine, 0.0], [0.0, 0.0, 1.0]])
    translation = -(cloud_rotation @ ego_position)
    dt = (cloud.header.stamp.sec - objects.header.stamp.sec
          + (cloud.header.stamp.nanosec - objects.header.stamp.nanosec) * 1e-9)
    remove = np.zeros(len(xyz), dtype=bool)
    protect = np.zeros(len(xyz), dtype=bool)
    for obj in objects.objects:
        pose = obj.kinematics.initial_pose_with_covariance.pose
        dims = np.array([obj.shape.dimensions.x, obj.shape.dimensions.y, obj.shape.dimensions.z])
        if obj.shape.type != Shape.BOUNDING_BOX or not np.isfinite(dims).all() or (dims <= 0).any():
            raise ValueError("cannot associate an object shape")
        obj_rotation = rotation(pose.orientation)
        center = np.array([pose.position.x, pose.position.y, pose.position.z])
        velocity = obj.kinematics.initial_twist_with_covariance.twist.linear
        center += obj_rotation @ np.array([velocity.x, velocity.y, velocity.z]) * dt
        if z_is_ground:
            center[2] += dims[2] / 2
        center = cloud_rotation @ center + translation
        box_rotation = cloud_rotation @ obj_rotation
        if not np.isfinite(center).all():
            raise ValueError("invalid object position or velocity")
        half = dims / 2
        # Broad phase avoids rotating every point for every object.
        extent = np.abs(box_rotation) @ (half + margin)
        candidates = np.flatnonzero(np.all(np.abs(xyz - center) <= extent, axis=1))
        if not len(candidates):
            continue
        local = (xyz[candidates] - center) @ box_rotation
        inside = np.all(np.abs(local) <= half + margin, axis=1)
        if bytes(obj.object_id.uuid) not in ignored_ids:
            protect[candidates[inside]] = True
        else:
            near_faces = np.abs(np.abs(local) - half) <= margin
            on_edge = np.count_nonzero(near_faces, axis=1) >= 2
            remove[candidates[inside & on_edge]] = True
    remove &= ~protect
    count = int(np.count_nonzero(remove))
    if count == 0:
        return cloud, 0
    output = PointCloud2()
    output.header = cloud.header
    output.height = 1
    output.width = len(xyz) - count
    output.fields = cloud.fields
    output.is_bigendian = cloud.is_bigendian
    output.point_step = cloud.point_step
    output.row_step = output.width * output.point_step
    output.is_dense = cloud.is_dense
    output.data = records[~remove].tobytes()
    return output, count
